server:
  port: 8080

spring:
  application:
    name: otus-backend

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
    build:
      enabled: true
