-- H2-совместимая схема для тестов (PostgreSQL mode)
CREATE TABLE IF NOT EXISTS questions (
    id   VARCHAR(36) PRIMARY KEY,
    text VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS answers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id VARCHAR(36) NOT NULL REFERENCES questions(id),
    text        VARCHAR(500) NOT NULL
);
